### ISSUE TITLE
when I execute the index_fuseki.sh,one error occured,please help to look at about this.

### ISSUE THREAD

**Issue by dswangGH** [AKSW/NLIWOD#4]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/jena/tdb/store/bulkloader2/CmdNodeTableBuilder : Unsupported major.minor version 52.0

**above error should happen when execute:**
$APACHE_JENA_BIN/tdbloader2 --loc=hawk_data_10-2015_dbpediatbd dbpedia_2015-10.owl disambiguations_en.ttl instance_types_en.ttl long_abstracts_en.ttl pnd_en.ttl  labels_en.ttl mappingbased_objects_en.ttl mappingbased_literals_en.ttl persondata_en.ttl specific_mappingbased_properties_en.ttl transitive_redirects_en.ttl en_surface_forms.ttl pagerank_en_2015-10.ttl redirect_labels.ttl

java -Xmx16G -cp $JENA_FUSEKI_JAR jena.textindexer --desc=fuseki_hawk_assembler.ttl

**Comment by dswangGH** [comment]
java version  on my machine is  "1.7.0_101"

**Comment by dswangGH** [comment]
16:05:27 INFO -- TDB Bulk Loader Start
 16:05:27 INFO Data Load Phase
 16:05:27 INFO Got 14 data files to load
 16:05:27 INFO Data file 1: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/dbpedia_2015-10.owl
 16:05:27 INFO Data file 2: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/disambiguations_en.ttl
 16:05:27 INFO Data file 3: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/instance_types_en.ttl
 16:05:27 INFO Data file 4: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/long_abstracts_en.ttl
 16:05:27 INFO Data file 5: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/pnd_en.ttl
 16:05:27 INFO Data file 6: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/labels_en.ttl
 16:05:27 INFO Data file 7: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/mappingbased_objects_en.ttl
 16:05:27 INFO Data file 8: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/mappingbased_literals_en.ttl
 16:05:27 INFO Data file 9: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/persondata_en.ttl
 16:05:27 INFO Data file 10: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/specific_mappingbased_properties_en.ttl
 16:05:27 INFO Data file 11: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/transitive_redirects_en.ttl
 16:05:27 INFO Data file 12: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/en_surface_forms.ttl
 16:05:27 INFO Data file 13: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/pagerank_en_2015-10.ttl
 16:05:27 INFO Data file 14: /home/ktgroup/wds/NLIWOD-master/qa.hawk/deploy-scripts/redirect_labels.ttl
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/jena/tdb/store/bulkloader2/CmdNodeTableBuilder : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
 16:05:27 ERROR Failed during data phase
Exception in thread "main" java.lang.UnsupportedClassVersionError: jena/textindexer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by RicardoUsbeck** [comment]
The error "Unsupported major.minor version 52.0" points toward the wrong java version, see http://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi . 

That is, you need to install jdk 1.8 since $APACHE_JENA_BIN uses JDK 1.8

**Comment by dswangGH** [comment]
thanks,I have got the problem solved,I ran the scripts again,and it give so many warnings like:
**WARN  [line: 2846221, col: 1 ] Bad IRI: <http://dbpedia.org/resource/EET_Nº7_Taller_Regional_Quilmes_(IMPA)> Code: 56/COMPATIBILITY_CHARACTER in PATH: Bad character**

I don't know the meaning of these warnings?

**Comment by RicardoUsbeck** [comment]
You can ignore the warnings. They occur due to the fact that DBpedia and Jena use different encodings.
